[book]
title = "twitch-dl Documentation"
description = "CLI tool for downloading videos from twitch.tv"
authors = ["Ivan Habunek"]
language = "en"
src = "docs"

[output.html]
additional-css = ["book.css"]
